# A TOML plugin for restate:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "restate"
type = "cli"
archs = ["macos", "linux"]

[resolve]
git-url = "https://github.com/restatedev/restate"

[platform.linux]
download-file = "restate-cli-{arch}-unknown-linux-musl.tar.xz"
checksum-file = "restate-cli-{arch}-unknown-linux-musl.tar.xz.sha256"
exe-path = "restate-cli-{arch}-unknown-linux-musl/restate"

[platform.macos]
download-file = "restate-cli-{arch}-apple-darwin.tar.xz"
checksum-file = "restate-cli-{arch}-apple-darwin.tar.xz.sha256"
exe-path = "restate-cli-{arch}-apple-darwin/restate"

[install]
download-url = "https://github.com/restatedev/restate/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/restatedev/restate/releases/download/v{version}/{checksum_file}"
